import os

APP_NAME = "personal_productivity_copilot"
MODEL_NAME = os.getenv("MODEL_NAME", "gemini-2.5-flash")

GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT")
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
GOOGLE_GENAI_USE_VERTEXAI = os.getenv("GOOGLE_GENAI_USE_VERTEXAI", "True")

FIRESTORE_USERS_COLLECTION = "users"
FIRESTORE_TASKS_COLLECTION = "tasks"
FIRESTORE_NOTES_COLLECTION = "notes"
FIRESTORE_PLANS_COLLECTION = "plans"
FIRESTORE_WORKFLOW_RUNS_COLLECTION = "workflow_runs"

CALENDAR_MCP_URL = os.getenv("CALENDAR_MCP_URL", "")
TASK_MCP_URL = os.getenv("TASK_MCP_URL", "")
NOTES_MCP_URL = os.getenv("NOTES_MCP_URL", "")